### ISSUE TITLE
Crash on javascript reload

### ISSUE THREAD

**Issue by gorangajic** [futurice/react-native-audio-toolkit#9]
It's crashing when reloading javascript

stacktrace
```
11-07 16:32:49.940 19681-19681/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.gambit, PID: 19681
                                                   java.lang.IllegalStateException
                                                       at android.media.MediaPlayer.getAudioSessionId(Native Method)
                                                       at com.futurice.rctaudiotoolkit.AudioPlayerModule.getInfo(AudioPlayerModule.java:218)
                                                       at com.futurice.rctaudiotoolkit.AudioPlayerModule.onHostPause(AudioPlayerModule.java:67)
                                                       at com.facebook.react.bridge.ReactContext.onHostPause(ReactContext.java:228)
                                                       at com.facebook.react.XReactInstanceManagerImpl.tearDownReactContext(XReactInstanceManagerImpl.java:827)
                                                       at com.facebook.react.XReactInstanceManagerImpl.access$500(XReactInstanceManagerImpl.java:110)
                                                       at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.onPreExecute(XReactInstanceManagerImpl.java:198)
                                                       at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:604)
                                                       at com.facebook.react.XReactInstanceManagerImpl.recreateReactContextInBackground(XReactInstanceManagerImpl.java:755)
                                                       at com.facebook.react.XReactInstanceManagerImpl.onJSBundleLoadedFromServer(XReactInstanceManagerImpl.java:738)
                                                       at com.facebook.react.XReactInstanceManagerImpl.access$100(XReactInstanceManagerImpl.java:110)
                                                       at com.facebook.react.XReactInstanceManagerImpl$1.onJSBundleLoadedFromServer(XReactInstanceManagerImpl.java:152)
                                                       at com.facebook.react.devsupport.DevSupportManagerImpl$19$1.run(DevSupportManagerImpl.java:747)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by FruitieX** [comment]
Hi, thanks for reporting.

Cleanup on reloading the JS bundle seems to be impossible right now in React Native, so we will unfortunately end up in an undefined state when doing JS reloads. [Here's a similar issue](https://github.com/react-native-community/react-native-video/issues/107) from a similar project, and audio playing forever after a JS reload is what you typically see as a result.

Maybe we can do something about the crash though, must investigate. Do you have an easy way of reproducing the error, I don't recall that simply playing back a long audio clip and then doing a JS reload would cause errors?

**Comment by davetao** [comment]
What would be the best approach to handling the illegal state exception? Could we at least catch the exception to prevent the application from catching?

**Comment by FruitieX** [comment]
Yeah, try/catch could probably be done if we don't find a better solution

**Comment by marcoacierno** [comment]
Update:

It also happens on production when the app goes in background

**Comment by jamsch** [comment]
Experiencing this issue in a production app as well. Also occurs when resuming the app from background mode.
![selection_022](https://user-images.githubusercontent.com/12927717/37376274-5fc093a8-2788-11e8-8dd3-1577371f9a15.png)

**Comment by jamsch** [comment]
Here's a different crash in comparison to the previous report however it's the same exception thrown as the OP.
![selection_023](https://user-images.githubusercontent.com/12927717/37495178-05beac0c-2911-11e8-8e86-2ee80cbc4da6.png)

**Comment by kidequinox** [comment]
Getting this also. Any idea on what could be causing this ?

**Comment by Jhonte** [comment]
Me too, android builds when going into background mode.
```
com.futurice.rctaudiotoolkit.AudioPlayerModule.getInfo (AudioPlayerModule.java:220)
com.futurice.rctaudiotoolkit.AudioPlayerModule.onHostPause (AudioPlayerModule.java:71)
```
Can it be this? 
` at android.media.MediaPlayer.getDuration(MediaPlayer.java)`

> you will have to check if the mediaPlayer is actually running before calling stop, else you will get IllegalStateException . Also you will get that when doing anything to a released MediaPlayer object. your code should be:
